In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.metrics import classification_report,confusion_matrix,f1_score,precision_score,recall_score,accuracy_score
from sklearn.model_selection import GridSearchCV
from time import time
from sklearn.neighbors import KNeighborsClassifier, NearestCentroid

In [2]:
df=pd.DataFrame(pd.read_csv('mnist_train1.csv'))
df2=pd.DataFrame(pd.read_csv('mnist_test1.csv'))

x_train1 = df.drop('label',axis=1)
y_train = df['label']
x_test1  = df2.drop('label',axis=1)
y_test  = df2['label']

In [3]:
t0=time()
scaler=MinMaxScaler()
scaler.fit(x_train1)
x_train=scaler.transform(x_train1)
x_test=scaler.transform(x_test1)
print("Standardization done in %0.3fs" % (time() - t0))

Standardization done in 1.308s


In [4]:
t0 = time()
pca=PCA(0.9)
pca.fit(x_train)
x_train=pca.transform(x_train)
x_test=pca.transform(x_test)
print("PCA transformation done in %0.3fs" % (time() - t0))

PCA transformation done in 12.315s


In [5]:
t0 = time()
model= KNeighborsClassifier(n_neighbors=1,p=2)
model.fit(x_train,y_train)
print("Training with knn done in %0.3fs" % (time() - t0))

Training with knn done in 3.467s


In [6]:
accur_train = []
accur = []
predictions_train=model.predict(x_train)
predictions_test=model.predict(x_test)
print("The accuracy in training set is {}".format(accuracy_score(predictions_train,y_train)))#format(model.score(x_train,y_train)))
print("The accuracy in testing set is {}".format(accuracy_score(predictions_test,y_test)))#format(model.score(x_test,y_test)))
print(confusion_matrix(y_test,predictions_test))
print('\n')
print(classification_report(y_test,predictions_test))
accur_train.append(accuracy_score(predictions_train,y_train))
accur.append(accuracy_score(predictions_test,y_test))

The accuracy in training set is 1.0
The accuracy in testing set is 0.9734
[[ 973    1    1    0    0    1    1    2    1    0]
 [   0 1130    3    0    1    0    1    0    0    0]
 [   5    1 1008    3    1    0    2   11    1    0]
 [   1    1    2  969    1   17    0    7    8    4]
 [   0    2    0    0  952    0    2    3    1   22]
 [   1    1    0    6    2  865    6    1    6    4]
 [   4    2    0    0    2    4  946    0    0    0]
 [   0   13    6    2    4    0    0  996    0    7]
 [   4    1    2   14    5   10    2    5  927    4]
 [   1    3    1    5   13    6    1   10    1  968]]


              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.98      1.00      0.99      1135
           2       0.99      0.98      0.98      1032
           3       0.97      0.96      0.96      1010
           4       0.97      0.97      0.97       982
           5       0.96      0.97      0.96       892
           6  

In [7]:
t0 = time()
model= KNeighborsClassifier(n_neighbors=3,p=2)
model.fit(x_train,y_train)
print("Training with knn done in %0.3fs" % (time() - t0))

Training with knn done in 3.938s


In [8]:
predictions_train=model.predict(x_train)
predictions_test=model.predict(x_test)
print("The accuracy in training set is {}".format(accuracy_score(predictions_train,y_train)))#format(model.score(x_train,y_train)))
print("The accuracy in testing set is {}".format(accuracy_score(predictions_test,y_test)))#format(model.score(x_test,y_test)))
print(confusion_matrix(y_test,predictions_test))
print('\n')
print(classification_report(y_test,predictions_test))
accur_train.append(accuracy_score(predictions_train,y_train))
accur.append(accuracy_score(predictions_test,y_test))

The accuracy in training set is 0.9886
The accuracy in testing set is 0.9735
[[ 974    1    1    0    0    1    2    1    0    0]
 [   0 1131    3    0    0    0    1    0    0    0]
 [   7    4 1002    2    1    0    0   14    2    0]
 [   0    1    5  977    1   11    0    7    5    3]
 [   2    6    0    0  952    0    4    2    0   16]
 [   3    1    0    9    2  866    4    1    2    4]
 [   5    3    0    0    2    3  945    0    0    0]
 [   0   16    6    0    2    0    0  998    0    6]
 [   6    1    3   15    6   13    3    3  921    3]
 [   5    5    2    9    9    3    1    3    3  969]]


              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.97      1.00      0.98      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.97      0.97      1010
           4       0.98      0.97      0.97       982
           5       0.97      0.97      0.97       892
           

In [10]:
clf = NearestCentroid()
clf.fit(x_train, y_train)
predictions_train=clf.predict(x_train)
predictions_test=clf.predict(x_test)
print("The accuracy in training set is {}".format(accuracy_score(predictions_train,y_train)))#format(model.score(x_train,y_train)))
print("The accuracy in testing set is {}".format(accuracy_score(predictions_test,y_test)))#format(model.score(x_test,y_test)))
print(confusion_matrix(y_test,predictions_test))
print('\n')
print(classification_report(y_test,predictions_test))
accur_train.append(accuracy_score(predictions_train,y_train))
accur.append(accuracy_score(predictions_test,y_test))

The accuracy in training set is 0.80745
The accuracy in testing set is 0.8196
[[ 877    0    7    2    2   58   25    1    7    1]
 [   0 1092   10    3    0    7    3    0   20    0]
 [  19   72  780   33   31    3   23   18   50    3]
 [   4   24   26  812    1   50    8   14   57   14]
 [   1   22    2    0  811    3   16    1   10  116]
 [  12   63    2  118   21  611   27   10   13   15]
 [  18   26   23    0   31   33  826    0    1    0]
 [   2   59   21    1   20    2    0  856   13   54]
 [  14   39   11   84   13   35   13    9  718   38]
 [  16   22    7   10   85   12    1   26   17  813]]


              precision    recall  f1-score   support

           0       0.91      0.89      0.90       980
           1       0.77      0.96      0.86      1135
           2       0.88      0.76      0.81      1032
           3       0.76      0.80      0.78      1010
           4       0.80      0.83      0.81       982
           5       0.75      0.68      0.72       892
          

In [17]:
accur_train

[1.0, 0.9886, 0.80745]

In [15]:
accur

[0.9734, 0.9735, 0.8196]